### ISSUE TITLE
Ingame Crash: Incompatible with Guardians Galore

### ISSUE THREAD

**Issue by Blunder-G** [lucaargolo/entity-banners#1]
When i in creative mode, i looked for moded creature banners and game crashed. It says "Entity Banners, Geckolib and Guardians Galore are suspected mods"

Here is crash report: 
[crash-2021-05-25_14.54.21-client.txt](https://github.com/lucaargolo/entity-banners/files/6539086/crash-2021-05-25_14.54.21-client.txt)

PS: Guardians Galore is a mod that add 20+ new and awsome looking animals/pets/guardians to the game. You must check it out!

**Comment by nicewithgreat** [comment]
I have a similar problem, when I use REI to browse items, it will crash

**Comment by lucaargolo** [comment]
I tried reproducing this bug using the latest Guardians Galore release and everything is working fine.
![image](https://user-images.githubusercontent.com/49497195/129427622-fa65ea1e-5867-45c1-b949-e2346bc18ca5.png)
I'll be closing this issue for now, if the incompatibility returns, feel free to reopen it.
